import { User } from './user.type';

export const USER_DATA: User[] = [
  {
    id: 'u1',
    avatar: 'https://i.pravatar.cc/120?u=alicej',
    name: 'Alice Johnson',
    email: 'alice.j@example.com',
    phoneNumber: '+12025550101',
    country: 'us',
    role: 'admin',
    status: 'active',
    createdAt: new Date('2023-01-15'),
  },
  {
    id: 'u2',
    avatar: 'https://i.pravatar.cc/120?u=bobs',
    name: 'Bob Smith',
    email: 'bob.smith@provider.net',
    phoneNumber: '+447700900102',
    country: 'gb',
    role: 'user',
    status: 'active',
    createdAt: new Date('2023-02-20'),
  },
  {
    id: 'u3',
    avatar: 'https://i.pravatar.cc/120?u=charlied',
    name: 'Charlie Davis',
    email: 'charlie.d@company.org',
    phoneNumber: '+33612345103',
    country: 'fr',
    role: 'manager',
    status: 'pending',
    createdAt: new Date('2023-03-10'),
  },
  {
    id: 'u4',
    avatar: 'https://i.pravatar.cc/120?u=dianap',
    name: 'Diana Prince',
    email: 'diana.p@justice.com',
    phoneNumber: '+491512345104',
    country: 'de',
    role: 'user',
    status: 'inactive',
    createdAt: new Date('2023-04-05'),
  },
  {
    id: 'u5',
    name: 'Ethan Hunt',
    avatar: 'https://i.pravatar.cc/120?u=ethanh',
    email: 'mission.impossible@agency.gov',
    phoneNumber: '+21622555105',
    country: 'tn',
    role: 'admin',
    status: 'active',
    createdAt: new Date('2023-05-12'),
  },
  {
    id: 'u6',
    avatar: 'https://i.pravatar.cc/120?u=fionag',
    name: 'Fiona Gallagher',
    email: 'fiona.g@southside.com',
    phoneNumber: '+353871235106',
    country: 'ie',
    role: 'user',
    status: 'active',
    createdAt: new Date('2023-06-18'),
  },
  {
    id: 'u7',
    avatar: 'https://i.pravatar.cc/120?u=georgem',
    name: 'George Miller',
    email: 'george.m@cinema.com',
    phoneNumber: '+61412345107',
    country: 'au',
    role: 'manager',
    status: 'pending',
    createdAt: new Date('2023-07-22'),
  },
  {
    id: 'u8',
    avatar: 'https://i.pravatar.cc/120?u=hannaab',
    name: 'Hannah Abbott',
    email: 'hannah.a@hufflepuff.edu',
    phoneNumber: '+447700900108',
    country: 'gb',
    role: 'user',
    status: 'active',
    createdAt: new Date('2023-08-30'),
  },
  {
    id: 'u9',
    avatar: 'https://i.pravatar.cc/120?u=ianw',
    name: 'Ian Wright',
    email: 'ian.w@football.uk',
    phoneNumber: '+447700900109',
    country: 'gb',
    role: 'user',
    status: 'inactive',
    createdAt: new Date('2023-09-14'),
  },
  {
    id: 'u10',
    avatar: 'https://i.pravatar.cc/120?u=juliar',
    name: 'Julia Roberts',
    email: 'julia.r@hollywood.com',
    phoneNumber: '+13105550110',
    country: 'us',
    role: 'manager',
    status: 'active',
    createdAt: new Date('2023-10-01'),
  },
  {
    id: 'u11',
    avatar: 'https://i.pravatar.cc/120?u=kevinh',
    name: 'Kevin Hart',
    email: 'kevin.h@comedy.com',
    phoneNumber: '+12125550111',
    country: 'us',
    role: 'user',
    status: 'active',
    createdAt: new Date('2023-10-25'),
  },
  {
    id: 'u12',
    avatar: 'https://i.pravatar.cc/120?u=laurap',
    name: 'Laura Palmer',
    email: 'laura.p@twinpeaks.com',
    phoneNumber: '+12065550112',
    country: 'us',
    role: 'admin',
    status: 'pending',
    createdAt: new Date('2023-11-11'),
  },
  {
    id: 'u13',
    avatar: 'https://i.pravatar.cc/120?u=michaels',
    name: 'Michael Scott',
    email: 'm.scott@dundermifflin.com',
    phoneNumber: '+15705550113',
    country: 'us',
    role: 'manager',
    status: 'active',
    createdAt: new Date('2023-11-28'),
  },
  {
    id: 'u14',
    avatar: 'https://i.pravatar.cc/120?u=nancyd',
    name: 'Nancy Drew',
    email: 'nancy.d@mystery.com',
    phoneNumber: '+18475550114',
    country: 'us',
    role: 'user',
    status: 'active',
    createdAt: new Date('2023-12-05'),
  },
  {
    id: 'u15',
    avatar: 'https://i.pravatar.cc/120?u=oscarw',
    name: 'Oscar Wilde',
    email: 'oscar.w@literature.ie',
    phoneNumber: '+353861235115',
    country: 'ie',
    role: 'user',
    status: 'inactive',
    createdAt: new Date('2023-12-12'),
  },
  {
    id: 'u16',
    avatar: 'https://i.pravatar.cc/120?u=peterp',
    name: 'Peter Parker',
    email: 'p.parker@dailybugle.com',
    phoneNumber: '+17185550116',
    country: 'us',
    role: 'admin',
    status: 'active',
    createdAt: new Date('2024-01-02'),
  },
  {
    id: 'u17',
    avatar: 'https://i.pravatar.cc/120?u=quinnf',
    name: 'Quinn Fabray',
    email: 'quinn.f@glee.edu',
    phoneNumber: '+14195550117',
    country: 'us',
    role: 'user',
    status: 'pending',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'u18',
    avatar: 'https://i.pravatar.cc/120?u=rileyr',
    name: 'Riley Reid',
    email: 'riley.r@example.com',
    phoneNumber: '+13105550118',
    country: 'us',
    role: 'manager',
    status: 'active',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'u19',
    avatar: 'https://i.pravatar.cc/120?u=stever',
    name: 'Steve Rogers',
    email: 's.rogers@avengers.com',
    phoneNumber: '+17185550119',
    country: 'us',
    role: 'admin',
    status: 'active',
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'u20',
    avatar: 'https://i.pravatar.cc/120?u=tonys',
    name: 'Tony Stark',
    email: 'tony@starkindustries.com',
    phoneNumber: '+12125550120',
    country: 'us',
    role: 'manager',
    status: 'active',
    createdAt: new Date('2024-02-10'),
  },
];
